#!/usr/bin/env python3
"""Build all airline pages + index.html"""
import json, os

D = os.path.dirname(os.path.abspath(__file__))
ADIR = os.path.join(D, "airlines")
os.makedirs(ADIR, exist_ok=True)

# Flags
def fl(r): # regional flag emoji
    return {"CA":"🇨🇦","PA":"🇵🇦","BO":"🇧🇴","UY":"🇺🇾","CO":"🇨🇴","CR":"🇨🇷","EC":"🇪🇨","PE":"🇵🇪",
            "VE":"🇻🇪","HN":"🇭🇳","BR":"🇧🇷","US":"🇺🇸","TC":"🇹🇨","CL":"🇨🇱","PG":"🇵🇾","SR":"🇸🇷",
            "SV":"🇸🇻","GT":"🇬🇹","KH":"🇰🇭","TH":"🇹🇭","ID":"🇮🇩","MY":"🇲🇾","MV":"🇲🇻","BD":"🇧🇩",
            "TW":"🇨🇳","CN":"🇨🇳","FJ":"🇫🇯","LK":"🇱🇰","GA":"🇬🇹","HK":"🇭🇰","KR":"🇰🇷","LA":"🇱🇦",
            "MM":"🇲🇲","NP":"🇳🇵","PH":"🇵🇭","PG2":"🇵🇬","BN":"🇧🇳","LK2":"🇱🇰","SB":"🇸🇧",
            "IN":"🇮🇳","LK3":"🇱🇰","VN":"🇻🇳","KZ":"🇰🇿","IL":"🇮🇱","AZ":"🇦🇿","EG":"🇪🇬",
            "AE":"🇦🇪","BH":"🇧🇭","JO":"🇯🇴","AF2":"🇦🇫","KW":"🇰🇼","LB":"🇱🇧","SA":"🇸🇦",
            "KZ2":"🇰🇿","TJ":"🇹🇯","TR":"🇹🇷","UZ":"🇺🇿","GA2":"🇬🇦","DZ":"🇩🇿","BF":"🇧🇫",
            "CI":"🇨🇮","NG":"🇳🇬","SN":"🇸🇳","SC":"🇸🇨","TZ":"🇹🇿","TG":"🇹🇬","GQ":"🇬🇶",
            "ZA2":"🇿🇦","KE":"🇰🇪","MZ":"🇲🇿","MG":"🇲🇬","MR":"🇲🇷","MA":"🇲🇦","RW":"🇷🇼",
            "ZA3":"🇿🇦","AO":"🇦🇴","CV":"🇨🇻","UG":"🇺🇬","RE":"🇷🇪","FR":"🇫🇷","LV":"🇱🇻",
            "NC":"🇳🇨","IT":"🇮🇹","RO2":"🇷🇴","MD":"🇲🇩","PF":"🇵🇫","ES":"🇪🇸","FR2":"🇫🇷",
            "HR":"🇭🇷","CY":"🇨🇾","GE":"🇬🇪","LU":"🇱🇺","NO":"🇳🇴","GR":"🇬🇷","RU":"🇷🇺",
            "PT":"🇵🇹","RO3":"🇷🇴","UA":"🇺🇦","FR3":"🇫🇷"}.get(r, "✈️")

A = []  # all airlines
def a(slug,code,kr,en,co,flagr,hub,hc,al,fw,dest,rt,ds,rg,img):
    A.append(locals().copy())

# ═══════════════ AMERICAS (31) ═══════════════
a("air-north","4N","에어 노스","Air North","캐나다","CA","화이트호스","YXY","없음","Boeing 737-400, ATR 42","15","화이트호스 ↔ 밴쿠버, 에드먼턴, 캘거리, 옐로나이프","1977년 설립. 캐나다 유콘 준주 지역 항공사. 북극곰 라이브러리 특징.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Air_North_Boeing_737-400_Combi_C-GNWN_YOW_2022.jpg/1280px-Air_North_Boeing_737-400_Combi_C-GNWN_YOW_2022.jpg")
a("air-panama","7P","에어 파나마","Air Panama","파나마","PA","파나마 시티","PAC","없음","Boeing 737-300, DHC-6","20","파나마 시티 ↔ 다비드, 보카스델토로, 쿠나얄라","파나마 국적 항공사. 카리브해 연안 섬과 내륙 연결.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Air_Panama_Boeing_737-3Y0_HP-1503_PAC.jpg/1280px-Air_Panama_Boeing_737-3Y0_HP-1503_PAC.jpg")
a("amaszonas","Z8","아마조나스 항공","Amaszonas","볼리비아","BO","코차밤바","CBB","없음","Bombardier CRJ-200/900","15","코차밤바 ↔ 라파스, 산타크루스, 수크레","볼리비아 지역 항공사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Amaszonas_Bombardier_CRJ-200ER_CP-2630_CBB_2017-04-25.jpg/1280px-Amaszonas_Bombardier_CRJ-200ER_CP-2630_CBB_2017-04-25.jpg")
a("amaszonas-uruguay","Z7","아마조나스 우루과이","Amaszonas Uruguay","우루과이","UY","몬테비데오","MVD","없음","Bombardier CRJ-200/900","8","몬테비데오 ↔ 부에노스아이레스, 아순시온","아마조나스 우루과이 자회사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bombardier_CRJ-200ER_%28Amaszonas_L%C3%ADnea_A%C3%A9rea%29.jpg/1280px-Bombardier_CRJ-200ER_%28Amaszonas_L%C3%ADnea_A%C3%A9rea%29.jpg")
a("avianca","AV","아비안카","Avianca","콜롬비아","CO","보고타","BOG","Star Alliance","Airbus A320/321, Boeing 787-8/9","80","보고타 ↔ 뉴욕, 마이애미, 마드리드, 리마, 산티아고","세계 2번째 오래된 항공사(1919). Star Alliance 멤버.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Avianca_Boeing_787-8_Dreamliner_N856AV.jpg/1280px-Avianca_Boeing_787-8_Dreamliner_N856AV.jpg")
a("avianca-costa-rica","LR","아비안카 코스타리카","Avianca Costa Rica","코스타리카","CR","산호세","SJO","Star Alliance","Airbus A320/321neo, ATR 72","30","산호세 ↔ 뉴욕, 로스앤젤레스, 과테말라, 마나과","아비안카 홀딩스 산하.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg/1280px-Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg")
a("avianca-ecuador","2K","아비안카 에콰도르","Avianca Ecuador","에콰도르","EC","키토","UIO","Star Alliance","Airbus A320/A319, ATR 72","15","키토 ↔ 보고타, 리마, 과야킬","아비안카 홀딩스 에콰도르.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg/1280px-Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg")
a("avianca-peru","T0","아비안카 페루","Avianca Peru","페루","PE","리마","LIM","Star Alliance","Airbus A320/A319, ATR 72","15","리마 ↔ 보고타, 키토, 산티아고","아비안카 홀딩스 페루.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg/1280px-Avianca_El_Salvador_ATR_72-600_%28EI-LPD%29.jpg")
a("avior-airlines","9V","아비오르 항공","Avior Airlines","베네수엘라","VE","바르키시메토","BRM","없음","Boeing 737-200, Embraer E-190","12","바르키시메토 ↔ 카라카스, 마르가리타섬","베네수엘라 민간 항공사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Avior_Airlines_Boeing_737-200_Adv._YV-1023.jpg/1280px-Avior_Airlines_Boeing_737-200_Adv._YV-1023.jpg")
a("calm-air","MO","캄 에어","Calm Air","캐나다","CA","위니펙","YWG","없음","ATR 42, DHC-6, Saab 340","15","위니펙 ↔ 체르칠, 랭커스터","1962년 설립. 매니토바주 항공 인프라.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Calm_Air_ATR_42-300_C-FTNN.jpg/1280px-Calm_Air_ATR_42-300_C-FTNN.jpg")
a("clic-air","VE","클릭 에어","Clic Air","콜롬비아","CO","메데인","EOH","없음","Beechcraft 1900, Let L-410, Cessna Caravan","25","메데인 ↔ 카르타헤나, 부카라만가, 아라우카","콜롬비아 내륙 오지 연결.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Clic_Air_Beechcraft_1900D_HK-4423_-_MDE.jpg/1280px-Clic_Air_Beechcraft_1900D_HK-4423_-_MDE.jpg")
a("cm-airlines","H5","CM 항공","CM Airlines","온두라스","HN","테구시갈파","TGU","없음","BAe Jetstream 31, Cessna Caravan","10","테구시갈파 ↔ 라세이바, 로아탄","온두라스 국적 항공사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/CM_Airlines_%28cropped%29.png/1280px-CM_Airlines_%28cropped%29.png")
a("ecojet","8J","에코제트","Ecojet","캐나다","CA","캘거리","YYC","없음","De Havilland Dash 8-400","8","캘거리 ↔ 밴쿠버, 에드먼턴, 빅토리아","2024년 캐나다 신규 지역 항공사. 저탄소 친환경.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/De_Havilland_Canada_DHC-8-402_%28Dash_8-400%29_Scorpion_Aviation_February_2024.jpg/1280px-De_Havilland_Canada_DHC-8-402_%28Dash_8-400%29_Scorpion_Aviation_February_2024.jpg")
a("gol-linhas-aereas","G3","골 항공","Gol Linhas Aereas","브라질","BR","상파울루","GRU","없음","Boeing 737-700/800/MAX","100","상파울루 ↔ 리우, 브라질리아, 살바도르, 부에노스아이레스","브라질 최대 LCC. 시장 점유율 1위.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/GOL_Boeing_737-800_%28PR-GXL%29.jpg/1280px-GOL_Boeing_737-800_%28PR-GXL%29.jpg")
a("hawaiian-airlines","HA","하와이안 항공","Hawaiian Airlines","미국","US","호놀룰루","HNL","없음","Airbus A330, Boeing 787-9, Boeing 717","30","호놀룰루 ↔ 라스베이거스, 샌프란시스코, 도쿄, 서울, 시드니","미국 최고령 항공사 중 하나(1929). 태평양 횡단. '알로하 정신'.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Hawaiian_Airlines_Boeing_787-9_N784HA_HNL_2024-04-18.png/1280px-Hawaiian_Airlines_Boeing_787-9_N784HA_HNL_2024-04-18.png")
a("intercaribbean-airways","JY","인터카리비안 항공","InterCaribbean Airways","터크스케이커스","TC","프로비덴시알레스","PLS","없음","Embraer E-120/145, ATR 42","15","프로비덴시알레스 ↔ 킹스턴, 산토도밍고, 나소, 하바나","터크스케이커스 항공사. 카리브해 20+ 목적지.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/InterCaribbean_Airways_Embraer_ERJ-145_VQ-BSS.jpg/1280px-InterCaribbean_Airways_Embraer_ERJ-145_VQ-BSS.jpg")
a("lanhsa","","란사","LANHSA","온두라스","HN","라세이바","LCE","없음","Cessna 208, Let L-410","8","라세이바 ↔ 테구시갈파, 로아탄","1970년 설립. 온두라스 카리브 연안 항공사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Let_L-410_UVP-E_Turbolet_C-FTCA_-_Air_Creebec.jpg/1280px-Let_L-410_UVP-E_Turbolet_C-FTCA_-_Air_Creebec.jpg")
a("latam-airlines","LA","LATAM 항공","LATAM Airlines","칠레","CL","산티아고","SCL","없음","Boeing 787-8/9, 777-300ER, A320/321neo","100","산티아고 ↔ 마드리드, 런던, 시드니, 마이애미, 뉴욕, 상파울루","라틴아메리카 최대 항공사 그룹. Delta 전략 파트너.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("latam-airlines-brazil","JJ","LATAM 브라질","LATAM Airlines Brazil","브라질","BR","상파울루","GRU","없음","Boeing 767-300ER, 777-300ER, A320neo","60","상파울루 ↔ 마이애미, 뉴욕, 파리, 런던, 리스본","LATAM 그룹 브라질 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("latam-airlines-colombia","4C","LATAM 콜롬비아","LATAM Airlines Colombia","콜롬비아","CO","보고타","BOG","없음","Airbus A320/319/320neo","20","보고타 ↔ 마이애미, 뉴욕, 키토, 리마, 산티아고","LATAM 그룹 콜롬비아 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("latam-airlines-ecuador","XL","LATAM 에콰도르","LATAM Airlines Ecuador","에콰도르","EC","키토","UIO","없음","Airbus A320","8","키토 ↔ 과야킬, 리마, 보고타, 산티아고","LATAM 그룹 에콰도르 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("latam-airlines-paraguay","PZ","LATAM 파라과이","LATAM Airlines Paraguay","파나과이","PG","아순시온","ASU","없음","Airbus A320/A319, Boeing 767-300ER","10","아순시온 ↔ 부에노스아이레스, 산티아고, 상파울루","LATAM 그룹 파라과이 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("latam-airlines-peru","LP","LATAM 페루","LATAM Airlines Peru","페루","PE","리마","LIM","없음","Airbus A320/319/320neo, Boeing 767-300ER","25","리마 ↔ 보고타, 산티아고, 부에노스아이레스, 마이애미","LATAM 그룹 페루 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg/1280px-LATAM_Chile_Boeing_787-9_Dreamliner_CC-BGK.jpg")
a("pal-airlines","PB","PAL 항공","PAL Airlines","캐나다","CA","세인트존스","YYT","없음","De Havilland Dash 8-100/300, Boeing 737","30","세인트존스 ↔ 핼리팩스, 몬트리올, 토론토","캐나다 대서양 연안 지역 항공사.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/PAL_Airlines_de_Havilland_Canada_DHC-8-102_C-GPPA_St._John%27s.jpg/1280px-PAL_Airlines_de_Havilland_Canada_DHC-8-102_C-GPPA_St._John%27s.jpg")
a("porter-airlines","P3","포터 항공","Porter Airlines","캐나다","CA","토론토(빌리 비숍)","YTZ","없음","De Havilland Dash 8-400, Embraer E195-E2","40","토론토 ↔ 몬트리올, 오타와, 핼리팩스, 뉴욕, 시카고","캐나다 프리미엄 리저널. 비행 중 무료 와인 서비스.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Porter_Airlines_Embraer_E195-E2_C-GEAK.jpg/1280px-Porter_Airlines_Embraer_E195-E2_C-GEAK.jpg")
a("porter-airlines-canada","PD","포터 항공 캐나다","Porter Airlines Canada","캐나다","CA","토론토(빌리 비숍)","YTZ","없음","De Havilland Dash 8-400, Embraer E195-E2","40","토론토 ↔ 몬트리올, 오타와, 뉴욕, 워싱턴","포터 항공 캐나다 국내 운항 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Porter_Airlines_Embraer_E195-E2_C-GEAK.jpg/1280px-Porter_Airlines_Embraer_E195-E2_C-GEAK.jpg")
a("sky-airline","H2","스카이 항공","Sky Airline","칠레","CL","산티아고","SCL","없음","Airbus A320/321neo","20","산티아고 ↔ 리마, 보고타, 부에노스아이레스, 키토","칠레 LCC. 남미 서부 해안 주요 도시 연결.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Sky_Airline_Airbus_A321-200N_CC-BHB-2.jpg/1280px-Sky_Airline_Airbus_A321-200N_CC-BHB-2.jpg")
a("sky-airlines-peru","H8","스카이 항공 페루","Sky Airline Peru","페루","PE","리마","LIM","없음","Airbus A320neo, A319","10","리마 ↔ 산티아고, 쿠스코, 아레키파","스카이 항공 페루 법인.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Sky_Airline_Airbus_A321-200N_CC-BHB-2.jpg/1280px-Sky_Airline_Airbus_A321-200N_CC-BHB-2.jpg")
a("surinam-airways","PY","수리남 항공","Surinam Airways","수리남","SR","파라마리보","PBM","없음","Boeing 737-700/800, Airbus A340-300","10","파라마리보 ↔ 암스테르담, 마이애미, 아루바, 트리니다드","수리남 국적 항공사. 남미 북부에서 유럽·북미 연결.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Surinam_Airways_Boeing_737-8AS_PZ-TCP.jpg/1280px-Surinam_Airways_Boeing_737-8AS_PZ-TCP.jpg")
a("taca","TA","타카 항공","TACA","엘살바도르","SV","산살바도르","SAL","Star Alliance","Airbus A320/321, ATR 72","40","산살바도르 ↔ 과테말라, 마나과, 산호세, 테구시갈파","1931년 설립. 중미 전통 항공사. 아비안카 그룹 통합.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/TACA_A320-200_%283749889531%29.jpg/1280px-TACA_A320-200_%283749889531%29.jpg")
a("tag-airlines","5U","TAG 항공","TAG Airlines","과테말라","GT","과테말라 시티","GUA","없음","Cessna 208 Caravan, Beechcraft 1900","10","과테말라 시티 ↔ 플로레스(티칼), 케찰테낭고, 산호세","과테말라 지역 항공사. 마야 문명 유적 티칼(플로레스) 연결.","americas","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Cessna_208B_Grand_Caravan_TAG_Airlines_TG-TAG1.jpg/1280px-Cessna_208B_Grand_Caravan_TAG_Airlines_TG-TAG1.jpg")

# ═══════════════ ASIA & OCEANIA (34) ═════════a("air-cambodia","K6","에어 캄보디아","Air Cambodia","캄보디아","KH","프놈펜","PNH","없음","Airbus A320","10","프놈펜 ↔ 시엠립, 방콕, 호치민, 싱가포르","캄보디아 국적 항공사. 앙코르와트 관문.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Airbus_A320-232_Air_Cambodia.jpg/1280px-Airbus_A320-232_Air_Cambodia.jpg")
a("bangkok-airways","PG","방콕 항공","Bangkok Airways","태국","TH","방콕(수와나품)","BKK","없음","Airbus A319/320, ATR 72-500","30","방콕 ↔ 푸껫, 코사무이, 치앙마이, 루앙프라방, 시엠립","아시아 최초 사유 지역 항공사(1968). 관광지 항공 특화.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Bangkok_Airways_Airbus_A320-200_HS-PGP.jpg/1280px-Bangkok_Airways_Airbus_A320-200_HS-PGP.jpg")
a("batik-air","ID","바티크 에어","Batik Air","인도네시아","ID","자카르타","CGK","없음","Airbus A320/A330, Boeing 737-800/900","70","자카르타 ↔ 발리, 메단, 마카사르, 싱가포르, 쿠알라룸푸르","인도네시아 라이온 에어 그룹의 풀서비스 항공사.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Batik_Air_Airbus_A320-200_PK-BRN.jpg/1280px-Batik_Air_Airbus_A320-200_PK-BRN.jpg")
a("batik-air-malaysia","OD","바티크 에어 말레이시아","Batik Air Malaysia","말레이시아","MY","쿠알라룸푸르","KUL","없음","Airbus A320, Boeing 737-800","20","쿠알라룸푸르 ↔ 자카르타, 발리, 싱가포르, 코타키나발루","바티크 에어의 말레이시아 법인.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Batik_Air_Airbus_A320-200_PK-BRN.jpg/1280px-Batik_Air_Airbus_A320-200_PK-BRN.jpg")
a("beijing-capital-airlines","JD","베이징 수도 항공","Beijing Capital Airlines","중국","CN","베이징","PEK","없음","Airbus A320/A330","50","베이징 ↔ 상하이, 구이양, 하이커우, 청두, 시안","중국 하이난항공 그룹 산하. 국내선 위주.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Beijing_Capital_Airlines_Airbus_A330-243_B-8207.jpg/1280px-Beijing_Capital_Airlines_Airbus_A330-243_B-8207.jpg")
a("beond","B4","비온드","beOnd","몰디브","MV","말레","MLE","없음","Airbus A321neo","5","말레 ↔ 뭄바이, 델리, 두바이, 뮌헨, 밀라노","몰디브 프리미엄 항공사(2023). 럭셔리 여행 특화.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Airbus_A321-200_CFM_INTL_LEAP-1A32N.jpg/1280px-Airbus_A321-200_CFM_INTL_LEAP-1A32N.jpg")
a("biman-bangladesh-airlines","BG","비만 방글라데시 항공","Biman Bangladesh Airlines","방글라데시","BD","다카","DAC","없음","Boeing 777-300ER, 787-8, Airbus A310","20","다카 ↔ 델리, 콜카타, 방콕, 쿠알라룸푸르, 두바이, 런던","방글라데시 국적 항공사(1972). 벵골의 마하파드마 새 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Biman_Bangladesh_Boeing_777-300ER_S2-AFE.jpg/1280px-Biman_Bangladesh_Boeing_777-300ER_S2-AFE.jpg")
a("china-airlines","CI","차이나 에어라인","China Airlines","대만","TW","타이베이(타오위안)","TPE","SkyTeam","Airbus A350-900, Boeing 777-300ER, 737-800","120","타이베이 ↔ 서울, 도쿄, 홍콩, 싱가포르, 로스앤젤레스, 런던, 프랑크푸르트","대만 최대 항공사(1959). SkyTeam 멤버. 매화 문양 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/China_Airlines_Boeing_777-300ER_B-18717.jpg/1280px-China_Airlines_Boeing_777-300ER_B-18717.jpg")
a("donghai-airlines","DZ","둥하이 항공","Donghai Airlines","중국","CN","선전","SZX","없음","Boeing 737-800","20","선전 ↔ 베이징, 상하이, 청두, 쿤밍","중국 화동(동부) 지역 항공사. 화물 겸용.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Donghai_Airlines_Boeing_737-800.jpg/1280px-Donghai_Airlines_Boeing_737-800.jpg")
a("fiji-airways","FJ","피지 항공","Fiji Airways","피지","FJ","난디","NAN","없음","Airbus A330-200/neo, Boeing 737-8/MAX","20","난디 ↔ 오클랜드, 시드니, 로스앤젤레스, 샌프란시스코, 홍콩","피지 국적 항공사(1951). 남태평양의 하늘 다리. 코코넛 트리 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Fiji_Airways_Airbus_A330-200_DQ-FJH.jpg/1280px-Fiji_Airways_Airbus_A330-200_DQ-FJH.jpg")
a("fits-air","8D","핏에어","FitsAir","스리랑카","LK","콜롬보","CMB","없음","Airbus A320, Antonov An-12","5","콜롬보 ↔ 첸나이, 마레, 티루치라팔리","스리랑카 화물 특화 항공사.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/FitsAir_Antonov_An-12BK.jpg/1280px-FitsAir_Antonov_An-12BK.jpg")
a("garuda-indonesia","GA","가루다 인도네시아 항공","Garuda Indonesia","인도네시아","ID","자카르타","CGK","SkyTeam","Airbus A330-300/neo, Boeing 777-300ER, 737-800/Max","80","자카르타 ↔ 발리, 메단, 싱가포르, 도쿄, 암스테르담, 런던","인도네시아 국적 항공사(1949). SkyTeam 멤버. 인도네시아 문양 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Garuda_Indonesia_Boeing_777-300ER_PK-GIG.jpg/1280px-Garuda_Indonesia_Boeing_777-300ER_PK-GIG.jpg")
a("greater-bay-airlines","HB","그레이터 베이 항공","Greater Bay Airlines","홍콩","HK","홍콩","HKG","없음","Boeing 737-800","10","홍콩 ↔ 방콕, 세부, 나하","홍콩 신규 항공사(2021). 대만해협 주변 노선.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Greater_Bay_Airlines_Boeing_737-800.jpg/1280px-Greater_Bay_Airlines_Boeing_737-800.jpg")
a("hong-kong-airlines","HX","홍콩 항공","Hong Kong Airlines","홍콩","HK","홍콩","HKG","없음","Airbus A320/321, A330-300","30","홍콩 ↔ 베이징, 상하이, 방콕, 오키나와, 삿포로","홍콩 기반 항공사. 중국 본토와 아시아 주요 도시 연결.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hong_Kong_Airlines_Airbus_A330-300.jpg/1280px-Hong_Kong_Airlines_Airbus_A330-300.jpg")
a("jeju-air","7C","제주에어","Jeju Air","한국","KR","제주","CJU","없음","Boeing 737-800","20","제주 ↔ 김포, 부산, 도쿄(나리타), 오사카, 베이징, 상하이, 다낭","한국 최대 LCC(2005). 제주도 노선 핵심. 파란색 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Jeju_Air_Boeing_737-800_HL8241.jpg/1280px-Jeju_Air_Boeing_737-800_HL8241.jpg")
a("korean-air","KE","대한항공","Korean Air","한국","KR","인천","ICN","SkyTeam","Boeing 777-300ER, 787-9/10, 737-8, A330-300, A380","120","인천 ↔ 도쿄, 상하이, 베이징, 홍콩, 싱가포르, 뉴욕, 런던, 파리, 로스앤젤레스","한국 국적 항공사(1962). SkyTeam 멤버. 홍학(Taegeuk) 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Korean_Air_Boeing_777-300ER_HL7782.jpg/1280px-Korean_Air_Boeing_777-300ER_HL7782.jpg")
a("kunming-airlines","KY","쿤밍 항공","Kunming Airlines","중국","CN","쿤밍","KMG","없음","Boeing 737-700/800","30","쿤밍 ↔ 베이징, 상하이, 광저우, 청두, 시안","중국 윈난성 기반 항공사. 하이난항공 그룹 산하.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Donghai_Airlines_Boeing_737-800.jpg/1280px-Donghai_Airlines_Boeing_737-800.jpg")
a("lao-airlines","QV","라오 항공","Lao Airlines","라오스","LA","비엔티안","VTE","없음","Airbus A320, ATR 72","20","비엔티안 ↔ 루앙프라방, 파크세, 방콕, 하노이, 싱가포르","라오스 국적 항공사(1976). 메콩강 유역 항공 서비스.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Lao_Airlines_Airbus_A320-200_RDPL-34193.jpg/1280px-Lao_Airlines_Airbus_A320-200_RDPL-34193.jpg")
a("malaysia-airlines","MH","말레이시아 항공","Malaysia Airlines","말레이시아","MY","쿠알라룸푸르","KUL","Oneworld","Airbus A330-300/neo, Boeing 737-800, 737 MAX","60","쿠알라룸푸르 ↔ 싱가포르, 방콕, 도쿄, 런던, 파리, 시드니","말레이시아 국적 항공사(1947). Oneworld 멤버. 켈라와시(Kelawar) 문양.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Malaysia_Airlines_Boeing_737-800_9M-MTS.jpg/1280px-Malaysia_Airlines_Boeing_737-800_9M-MTS.jpg")
a("maswings","","MAS윙스","MASWings","말레이시아","MY","코타키나발루","BKI","없음","ATR 72-500, de Havilland Canada DHC-6","20","코타키나발루 ↔ 산다칸, 라부안, 미리, 타와우, 브루나이","말레이시아 사바·사라왁 지역 항공사. 보르네오 내륙 연결.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/MASWings_ATR_72-500.jpg/1280px-MASWings_ATR_72-500.jpg")
a("myanmar-airways-intl","8M","미얀마 국제항공","Myanmar Airways Intl","미얀마","MM","양곤","RGN","없음","Airbus A319/320, Boeing 737-800","20","양곤 ↔ 싱가포르, 방콕, 첸나이, 캘커타","미얀마 국적 항공사(1993). 파가다(Pagoda) 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Myanmar_Airways_International_Boeing_737-800.jpg/1280px-Myanmar_Airways_International_Boeing_737-800.jpg")
a("nepal-airlines","RA","네팔 항공","Nepal Airlines","네팔","NP","카트만두","KTM","없음","Airbus A320, de Havilland Canada DHC-6","10","카트만두 ↔ 델리, 방콕, 두바이, 쿠알라룸푸르, 홍콩","네팔 국적 항공사(1958). 히말라야 산맥 운항 전문.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Nepal_Airlines_Airbus_A320-200_9N-AKN.jpg/1280px-Nepal_Airlines_Airbus_A320-200_9N-AKN.jpg")
a("philippine-airlines","PR","필리핀 항공","Philippine Airlines","필리핀","PH","마닐라","MNL","없음","Airbus A330/350, Boeing 777-300ER","60","마닐라 ↔ 서울, 도쿄, 홍콩, 싱가포르, 로스앤젤레스, 뉴욕","필리핀 국적 항공사(1941). 아시아 최초 상업 항공사 중 하나.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Philippine_Airlines_Airbus_A350-941_RP-C3597.jpg/1280px-Philippine_Airlines_Airbus_A350-941_RP-C3597.jpg")
a("png-air","CG","PNG 항공","PNG Air","파푸아뉴기니","PG2","포트모르즈비","POM","없음","de Havilland Canada DHC-8, ATR 42","20","포트모르즈비 ↔ 라에, 마당, 고로카, 트로브리안 제도","파푸아뉴기니 지역 항공사. 험준한 열대 지형 운항.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/PNG_Air_De_Havilland_Canada_DHC-8-100.jpg/1280px-PNG_Air_De_Havilland_Canada_DHC-8-100.jpg")
a("royal-brunei","BI","로열 브루나이 항공","Royal Brunei Airlines","브루나이","BN","반다르스리브가원","BWN","없음","Airbus A320neo, Boeing 787-8","20","반다르스리브가원 ↔ 쿠알라룸푸르, 싱가포르, 자카르타, 도쿄, 두바이, 런던","브루나이 국적 항공사(1974).","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Royal_Brunei_Boeing_787-8_Dreamliner_V8-DLA.jpg/1280px-Royal_Brunei_Boeing_787-8_Dreamliner_V8-DLA.jpg")
a("shandong-airlines","SC","산둥 항공","Shandong Airlines","중국","CN","제남","TNA","없음","Boeing 737-800","80","제남 ↔ 베이징, 상하이, 광저우, 청두, 하얼빈","중국 산둥성 기반 항공사. 산둥항공 그룹 산하.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Shandong_Airlines_Boeing_737-800_B-5140.jpg/1280px-Shandong_Airlines_Boeing_737-800_B-5140.jpg")
a("sichuan-airlines","3U","쓰촨 항공","Sichuan Airlines","중국","CN","청두","CTU","없음","Airbus A319/320/321, A330","130","청두 ↔ 베이징, 상하이, 구이양, 라사, 쿤밍","중국 쓰촨성 기반 항공사. 티베트 라사 노선 운항.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sichuan_Airlines_Airbus_A330-300.jpg/1280px-Sichuan_Airlines_Airbus_A330-300.jpg")
a("solomon-airlines","IE","솔로몬 항공","Solomon Islands Airlines","솔로몬 제도","SB","호니아라","HIR","없음","de Havilland Canada DHC-6 Twin Otter","20","호니아라 ↔ 아우키, 기조, 멘다나, 노우카","솔로몬 제도 국적 항공사. 태평양 섬 간 연결.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Solomon_Airlines_De_Havilland_Canada_DHC-6-300_Twin_Otter_H4-SIL.jpg/1280px-Solomon_Airlines_De_Havilland_Canada_DHC-6-300_Twin_Otter_H4-SIL.jpg")
a("spicejet","SG","스파이스제트","SpiceJet","인도","IN","델리","DEL","없음","Boeing 737-700/800/900, Bombardier Q400","60","델리 ↔ 뭄바이, 첸나이, 방콕, 두바이, 가르메","인도 LCC. 붉은색 라이브러리. 인도 국내선 핵심.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/SpiceJet_Boeing_737-800_VT-SPY.jpg/1280px-SpiceJet_Boeing_737-800_VT-SPY.jpg")
a("srilankan-airlines","UL","스리랑카 항공","SriLankan Airlines","스리랑카","LK3","콜롬보","CMB","Oneworld","Airbus A320/321/330","40","콜롬보 ↔ 뭄바이, 델리, 방콕, 싱가포르, 도쿄, 런던","스리랑카 국적 항공사(1979). Oneworld 멤버.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/SriLankan_Airlines_Airbus_A330-243_4R-ALH.jpg/1280px-SriLankan_Airlines_Airbus_A330-243_4R-ALH.jpg")
a("thai-airways","TG","태국항공","Thai Airways","태국","TH","방콕(수와나품)","BKK","Star Alliance","Airbus A350-900, Boeing 777-300ER, 787-8, 737-800","80","방콕 ↔ 서울, 도쿄, 홍콩, 싱가포르, 런던, 프랑크푸르트, 파리, 로스앤젤레스","태국 국적 항공사(1960). Star Alliance 멤버. 태국 문양 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Thai_Airways_Boeing_777-300ER_HS-TKQ.jpg/1280px-Thai_Airways_Boeing_777-300ER_HS-TKQ.jpg")
a("thai-lion-air","SL","타이 라이온 에어","Thai Lion Air","태국","TH","방콕(돈므앙)","DMK","없음","Boeing 737-800/900ER","30","방콕 ↔ 치앙마이, 푸껫, 쿠알라룸푸르, 자카르타, 싱가포르","인도네시아 라이온 에어의 태국 LCC 법인.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Thai_Lion_Air_Boeing_737-9BER_HS-LTL.jpg/1280px-Thai_Lion_Air_Boeing_737-9BER_HS-LTL.jpg")
a("thai-vietjet-air","VZ","태국 비엣젯 에어","Thai Vietjet Air","태국","TH","방콕(수와나품)","BKK","없음","Airbus A320/321","20","방콕 ↔ 푸껫, 치앙마이, 호치민, 하노이","비엣젯 에어의 태국 법인.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/VietJet_Air_Airbus_A321-200.jpg/1280px-VietJet_Air_Airbus_A321-200.jpg")
a("vietjet-air","VJ","비엣젯 에어","VietjetAir","베트남","VN","호치민","SGN","없음","Airbus A320/321","70","호치민 ↔ 하노이, 다낭, 나트랑, 방콕, 싱가포르, 서울","베트남 최대 LCC. 노란 바이크 라이브러리 특징.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/VietJet_Air_Airbus_A321-200.jpg/1280px-VietJet_Air_Airbus_A321-200.jpg")
a("vietnam-airlines","VN","베트남 항공","Vietnam Airlines","베트남","VN","하노이","HAN","SkyTeam","Airbus A350-900, Boeing 787-9, A321neo","90","하노이/호치민 ↔ 서울, 도쿄, 홍콩, 싱가포르, 파리, 런던, 프랑크푸르트","베트남 국적 항공사(1956). SkyTeam 멤버. 하늘색 로터스 라이브러리.","asia","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Vietnam_Airlines_Boeing_787-9_Dreamliner_VN-A885.jpg/1280px-Vietnam_Airlines_Boeing_787-9_Dreamliner_VN-A885.jpg")

# ═══════════════ MIDDLE EAST & CENTRAL ASIA (17) ═══════════════
a("air-astana","KC","에어 아스타나","Air Astana","카자흐스탄","KZ","아스타나","TSE","없음","Airbus A321LR/neo, Boeing 767-300ER, Embraer E190","60","아스타나 ↔ 알마티, 두바이, 이스탄불, 모스크바, 베이징, 런던","카자흐스탄 국적 항공사(2001). 중앙아시아 최대 항공사.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Air_Astana_Boeing_767-300ER_P4-MEY.jpg/1280px-Air_Astana_Boeing_767-300ER_P4-MEY.jpg")
a("arkia","IZ","아르키아 항공","Arkia","이스라엘","IL","텔아비브","TLV","없음","Airbus A321neo, Boeing 767-300ER","20","텔아비브 ↔ 파리, 런던, 로마, 아테네, 두바이, 리마솔","이스라엘 2번째 항공사(1948). 관광지 전문.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Arkia_Boeing_767-300_ER_4X-AVK.jpg/1280px-Arkia_Boeing_767-300_ER_4X-AVK.jpg")
a("azerbaijan-airlines","J2","아제르바이잔 항공","Azerbaijan Airlines","아제르바이잔","AZ","바쿠","GYD","없음","Airbus A320/321, Boeing 767-300ER, 787-8","25","바쿠 ↔ 이스탄불, 두바이, 모스크바, 런던, 베이징","아제르바이잔 국적 항공사(1992).","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Azerbaijan_Airlines_Airbus_A319-100_4K-AZ17.jpg/1280px-Azerbaijan_Airlines_Airbus_A319-100_4K-AZ17.jpg")
a("egyptair","MS","이집트항공","Egyptair","이집트","EG","카이로","CAI","Star Alliance","Airbus A320/321neo, Boeing 777-300ER, 787-9","80","카이로 ↔ 두바이, 리야드, 이스탄불, 런던, 파리, 뉴욕, 도쿄","이집트 국적 항공사(1932). Star Alliance 멤버. 호루스 라이브러리.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/EgyptAir_Boeing_777-300ER_SU-GBI.jpg/1280px-EgyptAir_Boeing_777-300ER_SU-GBI.jpg")
a("flydubai","FZ","플라이두바이","FlyDubai","아랍에미리트","AE","두바이","DXB","없음","Boeing 737-800/MAX 8/9/10","110","두바이 ↔ 리야드, 제다, 이스탄불, 텔아비브, 키이프, 모스크바","두바이 LCC(2009). 보잉 737 MAX 대량 도입. 중동·아프리카·CIS 노선.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/FlyDubai_Boeing_737-8_MAX_8_A6-FKD.jpg/1280px-FlyDubai_Boeing_737-8_MAX_8_A6-FKD.jpg")
a("gulf-air","GF","걸프 에어","Gulf Air","바레인","BH","마나마","BAH","없음","Airbus A320neo, A321neo, Boeing 787-9","40","마나마 ↔ 두바이, 리야드, 이스탄불, 런던, 파리, 뭄바이","바레인 국적 항공사(1950). 걸프 지역 최고령 항공사 중 하나.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Gulf_Air_Boeing_787-9_Dreamliner_A9C-FB.jpg/1280px-Gulf_Air_Boeing_787-9_Dreamliner_A9C-FB.jpg")
a("jordan-aviation","R5","요르단 항공","Jordan Aviation","요르단","JO","암만","AMM","없음","Airbus A320/321, Boeing 737-300/800","20","암만 ↔ 지다, 리야드, 바그다드, 이스탄불, 샤름엘셰이크","요르던 차터/정기 항공사(2000). 성지 순례 노선.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Jordan_Aviation_Airbus_A320-232_JY-AVP.jpg/1280px-Jordan_Aviation_Airbus_A320-232_JY-AVP.jpg")
a("kam-air","RQ","캄 에어","Kam Air","아프가니스탄","AF2","카불","KBL","없음","Boeing 737-300/400/500, Airbus A340","15","카불 ↔ 두바이, 이슬라마바드, 마자리샤리프, 헤라트","아프가니스탄 최대 민간 항공사(2003). 험준한 지형 운항.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Kam_Air_Boeing_737-500_YA-KAM.jpg/1280px-Kam_Air_Boeing_737-500_YA-KAM.jpg")
a("kuwait-airways","KU","쿠웨이트 항공","Kuwait Airways","쿠웨이트","KW","쿠웨이트 시티","KWI","없음","Airbus A320neo, A330-200/800, Boeing 777-300ER","30","쿠웨이트 시티 ↔ 두바이, 리야드, 이스탄불, 런던, 파리, 뭄바이","쿠웨이트 국적 항공사(1953).","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Kuwait_Airways_Boeing_777-300ER_9K-AOM.jpg/1280px-Kuwait_Airways_Boeing_777-300ER_9K-AOM.jpg")
a("middle-east-airlines","ME","미들 이스트 항공","Middle East Airlines","레바논","LB","베이루트","BEY","SkyTeam","Airbus A320/321, A330-200","20","베이루트 ↔ 두바이, 리야드, 이스탄뷰, 런던, 파리","레바논 국적 항공사(1945). SkyTeam 멤버.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Middle_East_Airlines_Airbus_A321-200_OD-MEA.jpg/1280px-Middle_East_Airlines_Airbus_A321-200_OD-MEA.jpg")
a("nesma-airlines","NE","네스마 항공","Nesma Airlines","사우디아라비아","SA","하일","HAS","없음","Airbus A320/321, Boeing 737-500","15","하일 ↔ 리야드, 지다, 다만, 카이로, 알렉산드리아","사우디아라비아 지역 항공사(2010).","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nesma_Airlines_Airbus_A320-200.jpg/1280px-Nesma_Airlines_Airbus_A320-200.jpg")
a("royal-jordanian","RJ","로열 요르다니안","Royal Jordanian","요르단","JO","암만","AMM","Oneworld","Airbus A319/320/321, Boeing 787-8","50","암만 ↔ 두바이, 이스탄불, 런던, 파리, 뉴욕, 몬트리올","요르단 국적 항공사(1963). Oneworld 멤버.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Royal_Jordanian_Boeing_787-8_Dreamliner_JY-ANN.jpg/1280px-Royal_Jordanian_Boeing_787-8_Dreamliner_JY-ANN.jpg")
a("saudi-arabian-airlines","SV","사우디아","Saudi Arabian Airlines","사우디아라비아","SA","지다","JED","SkyTeam","Airbus A320/321neo, Boeing 777-300ER, 787-10","100","지다/리야드 ↔ 두바이, 이스탄불, 런던, 뉴욕, 자카르타, 마닐라","사우디아라비아 국적 항공사(1945). SkyTeam 멤버. 이슬람 성지 순례 항공.","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Saudi_Arabian_Boeing_777-300ER_HZ-AK21.jpg/1280px-Saudi_Arabian_Boeing_777-300ER_HZ-AK21.jpg")
a("scat-airlines","DV","스캣 항공","SCAT Airlines","카자흐스탄","KZ2","슈임켄트","CIT","없음","Boeing 737-300/500/800, Bombardier CRJ-200","30","슈임켄트 ↔ 아스타나, 알마티, 아크타우, 우랄스크","카자흐스탄 지역 항공사(1997).","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SCAT_Airlines_Boeing_737-500_UP-B7306.jpg/1280px-SCAT_Airlines_Boeing_737-500_UP-B7306.jpg")
a("somon-air","SZ","소몬 에어","Somon Air","타지키스탄","TJ","두샨베","DYU","없음","Boeing 737-300/800/900","15","두샨베 ↔ 두바이, 이스탄불, 알마티, 우파","타지키스탄 국적 항공사(2004).","middleeast","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Somon_Air_Boeing_737-300_E4-